language: R
cache: packages
sudo: true


env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
  - _R_CHECK_SYSTEM_CLOCK_=false

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - Rscript -e 'update.packages(ask = FALSE)'

r_github_packages:
  - r-lib/pkgdown
  - r-lib/covr

bioc_packages:
  - GEOquery

matrix:
  include:
  - r: devel
  - r: release
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
  - r: 3.5

after_success:
  - Rscript -e 'covr::codecov()'