# Write pkgdown/_brand.yml from the meta and color sections of the brand file.
# pkgdown reads this file instead of inst/brand/_brand.yml, because the font
# files in the brand file would be embedded in every page of the website.
# Run it from the package root after each change to inst/brand/_brand.yml.
brand <- yaml::read_yaml("inst/brand/_brand.yml")
header <- c(
  "# Generated by data-raw/brand-to-pkgdown.R from inst/brand/_brand.yml.",
  "# Do not edit by hand. Regenerate with:",
  "#   Rscript data-raw/brand-to-pkgdown.R"
)
writeLines(
  c(header, yaml::as.yaml(brand[c("meta", "color")])),
  "pkgdown/_brand.yml"
)
