# Write pkgdown/_brand.yml from the brand file without its fonts.
# pkgdown reads this file instead of inst/brand/_brand.yml, because the font
# files in the brand file would be embedded in every page of the website.
# The website loads its fonts from Google Fonts in pkgdown/_pkgdown.yml.
# Run it from the package root after each change to inst/brand/_brand.yml.
brand <- yaml::read_yaml("inst/brand/_brand.yml")
header <- c(
  "# Generated by data-raw/brand-to-pkgdown.R from inst/brand/_brand.yml.",
  "# Do not edit by hand. Regenerate with:",
  "#   Rscript data-raw/brand-to-pkgdown.R"
)
# The logo is dropped because its path would not resolve from pkgdown/.
typography <- brand$typography
typography$fonts <- NULL
for (name in c(
  "base",
  "headings",
  "monospace",
  "monospace-inline",
  "monospace-block"
)) {
  if (!is.list(typography[[name]])) {
    typography[[name]] <- NULL
  } else {
    typography[[name]]$family <- NULL
  }
}
brand$typography <- typography
writeLines(
  c(header, yaml::as.yaml(brand[c("meta", "color", "typography")])),
  "pkgdown/_brand.yml"
)
