#show: doc => nacho-report(
  title: [$title$],
$if(author)$
  author: [$author$],
$endif$
  prepared: [$nacho.prepared$],
  details: (
    ([Samples], [$nacho.samples$]),
    ([$nacho.unit$], [$nacho.units$]),
    ([Flagged], [$nacho.flagged$]),
    ([Normalization], [$nacho.method$]),
    ([RCC version], [$nacho.rcc_version$]),
    ([NACHO], [$nacho.nacho_version$]),
  ),
  generated: [Generated by NACHO $nacho.nacho_version$ on R $nacho.r_version$],
  footer-text: [NACHO $nacho.nacho_version$ · R $nacho.r_version$ · $nacho.date$],
$if(section-numbering)$
  sectionnumbering: "$section-numbering$",
$endif$
$if(toc)$
  toc: $toc$,
$endif$
$if(toc-title)$
  toc_title: [$toc-title$],
$endif$
  toc_depth: $toc-depth$,
  doc,
)
